apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","metadata":{"annotations":{},"labels":{"application":"stakaterbe","template":"openjdk18-web-basic-s2i","xpaas":"1.4.14"},"name":"stakaterbe","namespace":"exp-gcas7-build"},"spec":{"output":{"to":{"kind":"ImageStreamTag","name":"stakaterbe:latest"}},"resources":{"limits":{"cpu":1,"memory":"2Gi"},"requests":{"cpu":1,"memory":"2Gi"}},"source":{"contextDir":"","git":{"ref":"two","uri":"https://git.dhl.com/GCA-1200/GRAUsrMgmtFE.git"},"type":"Git"},"strategy":{"sourceStrategy":{"env":[{"name":"MAVEN_MIRROR_URL","value":"https://artifactory.dhl.com/maven-release"}],"forcePull":true,"from":{"kind":"ImageStreamTag","name":"java:8","namespace":"openshift"}},"type":"Source"},"triggers":[{"github":{"secret":"dummy"},"type":"GitHub"},{"generic":{"secret":"dummy"},"type":"Generic"},{"imageChange":{},"type":"ImageChange"},{"type":"ConfigChange"}]}}
  creationTimestamp: '2021-06-12T08:52:47Z'
  labels:
    application: stakaterbe
    template: openjdk18-web-basic-s2i
    xpaas: 1.4.14
  name: stakaterbe
  namespace: exp-gcas7-build
  resourceVersion: '1555643200'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/exp-gcas7-build/buildconfigs/stakaterbe
  uid: 8f8eac5e-cb5b-11eb-a867-0050569a205e
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'stakaterbe:latest'
  postCommit: {}
  resources:
    limits:
      cpu: '1'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: 'https://github.com/chandraawm/StakaterBE.git'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: MAVEN_MIRROR_URL
          value: 'https://artifactory.dhl.com/maven-release'
      forcePull: true
      from:
        kind: ImageStreamTag
        name: 'java:8'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: dummy
      type: GitHub
    - generic:
        secret: dummy
      type: Generic
    - imageChange:
        lastTriggeredImageID: >-
          docker-registry.default.svc:5000/openshift/java@sha256:b0c7bbc0df90ba817f01213a548a747796fc01e2b1933193de0df5c48d46d920
      type: ImageChange
    - type: ConfigChange
status:
  lastVersion: 7
